### ISSUE TITLE
[Meta] EMS v7.12

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-file-service#202]
It's time to prep EMS v7.12. We'll add corresponding issues to each item below.

- [x] File Service https://github.com/elastic/ems-file-service/pull/203
- [x] Tile Service
- [x] ems-client https://github.com/elastic/ems-client/pull/57
- [x] ems-landing-page https://github.com/elastic/ems-landing-page/pull/306
- [x] bump ems-client in kibana https://github.com/elastic/kibana/pull/90841
- [x] update ems-landing-page link in kibana
