### ISSUE TITLE
[Meta] EMS 7.13

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-file-service#206]
It's time to prep EMS v7.13. We'll add corresponding issues to each item below.
 
- [x] File Service https://github.com/elastic/ems-file-service/pull/207
- [x] Tile Service
- [x] ems-client https://github.com/elastic/ems-client/pull/59
- [x] ems-landing-page  https://github.com/elastic/ems-landing-page/pull/329
- [x] bump ems-client in kibana 
- [x] update ems-landing-page link in kibana

**Comment by jsanz** [comment]
EMS File service 7.13 deployed to production https://kibana-ci.elastic.co/job/elastic+ems-file-service+deploy/15/
