### ISSUE TITLE
[Meta] EMS 7.14

### ISSUE THREAD

**Issue by jsanz** [elastic/ems-file-service#220]
Starting the release work for 7.14 a bit early to give time for Kibana to leverage upcoming changes in ems-client regarding metadata published in EMS file manifests https://github.com/elastic/ems-client/pull/69

- [x] File Service #221
- [x] Tile Service
- [x] ems-client elastic/ems-client#70
- [x] ems-landing-page elastic/ems-landing-page#357
- [x] bump ems-client in kibana elastic/kibana#102910
- [x] update ems-landing-page link in kibana elastic/kibana#108102

**Comment by jsanz** [comment]
Regarding `File Service`, we already have published manifests up to future `7.16` but I will trigger the publish task to include the last fix #218

**Comment by jsanz** [comment]
`@elastic/ems-client 7.14.0` is available in npm registry @thomasneirynck  

https://www.npmjs.com/package/@elastic/ems-client

**Comment by jsanz** [comment]
Version 7.14 of the Landing Page is [live](https://maps.elastic.co/v7.14/).
