### ISSUE TITLE
[Meta] EMS 7.16

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-file-service#227]
It's time to update EMS to 7.16 prior to 7.16.0 Stack release.

- [x] File Service 
- [x] Tile Service
- [x] ems-client elastic/ems-client#81
- [x] ems-landing-page elastic/ems-landing-page#364
- [x] bump ems-client and ems-landing-page link in kibana elastic/kibana#114865
