### ISSUE TITLE
[Meta] EMS 8.0

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-file-service#228]
It's time to update EMS to 8.0 prior to 8.0.0 Stack release.

- [x] File Service https://github.com/elastic/ems-file-service/pull/229
- [x] Tile Service
- [x] ems-client https://github.com/elastic/ems-client/pull/82
- [x] ems-landing-page https://github.com/elastic/ems-landing-page/pull/365
- [x] bump ems-client and ems-landing-page link in kibana https://github.com/elastic/kibana/pull/116217
